<Project>

  <!-- Common properties -->
  <PropertyGroup>
    <Authors>Gilles TOURREAU</Authors>
    <Company>P.O.S Informatique</Company>
    <Product>P.O.S Informatique Visual Studio Templates</Product>
    <Copyright>Copyright (c) P.O.S Informatique. All rights reserved.</Copyright>
    <RepositoryUrl>https://github.com/PosInformatique/PosInformatique.VisualStudio.Templates</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <!-- Enable the last version of C# -->
    <LangVersion>latest</LangVersion>
    
    <!-- Disable the StyleCop 'XML comment analysis is disabled due to project configuration' warning. -->
    <NoWarn>$(NoWarn);SA0001;S3904</NoWarn>

    <!-- Enable implict usings -->
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\stylecop.json">
      <Link>stylecop.json</Link>
    </AdditionalFiles>
  </ItemGroup>

  <!-- Common NuGet packages -->
  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Add the default using directive for all the code -->
  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections.ObjectModel" />
  </ItemGroup>

</Project>