<Project>

  <!-- Common properties -->
  <PropertyGroup>
    <Authors>Gilles TOURREAU</Authors>
    <Company>P.O.S Informatique</Company>
    <Product>P.O.S Informatique Visual Studio Templates</Product>
    <Copyright>Copyright (c) P.O.S Informatique. All rights reserved.</Copyright>
    <RepositoryUrl>https://github.com/PosInformatique/PosInformatique.VisualStudio.Templates</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <!-- Enable the last version of C# -->
    <LangVersion>latest</LangVersion>

    <!-- Enable implict usings -->
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Add the default using directive for all the code -->
  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections.ObjectModel" />
  </ItemGroup>

</Project>