<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="editorconfig" Version="0.16.2" />
    <PackageVersion Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" />
    <PackageVersion Include="Microsoft.VisualStudio.TemplateWizardInterface" Version="17.10.40170" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15" />
    <PackageVersion Include="Microsoft.VSSDK.BuildTools" Version="18.5.40034" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.27.0.140913" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <PackageVersion Include="System.ValueTuple" Version="4.6.2" />
    <PackageVersion Include="Verify.XunitV3" Version="31.24.2" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>
</Project>