<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>PosInformatique.VisualStudio.Templates.Files</RootNamespace>
    <AssemblyName>PosInformatique.VisualStudio.Templates.Files</AssemblyName>
    <GeneratePkgDefFile>false</GeneratePkgDefFile>
    <IncludeAssemblyInVSIXContainer>false</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>false</IncludeDebugSymbolsInLocalVSIXDeployment>
    <CreateVsixContainer>false</CreateVsixContainer>
    <DeployExtension>false</DeployExtension>
    <DeployVSTemplates>false</DeployVSTemplates>
    <CopyVsixManifestToOutput>false</CopyVsixManifestToOutput>
    <CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>false</CopyOutputSymbolsToOutputDirectory>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SkipCompilerExecution>true</SkipCompilerExecution>
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectCapability Include="CreateVsixContainer" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Remove="Class.cs" />
    <Compile Remove="Exception.cs" />
    <Compile Remove="ExceptionUnitTest.cs" />
    <Compile Remove="Interface.cs" />
    <Compile Remove="RazorComponent.razor.cs" />
    <Compile Remove="XUnitTest.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="Class.cs" />
    <None Include="Exception.cs" />
    <None Include="ExceptionUnitTest.cs" />
    <None Include="Interface.cs" />
    <None Include="RazorComponent.razor" />
    <None Include="RazorComponent.razor.cs" />
    <None Include="XUnitTest.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <VSTemplate Include="Class.vstemplate" OutputSubPath="P.O.S Informatique" />
    <VSTemplate Include="Exception.vstemplate" OutputSubPath="P.O.S Informatique" />
    <VSTemplate Include="ExceptionUnitTest.vstemplate" OutputSubPath="P.O.S Informatique" />
    <VSTemplate Include="Interface.vstemplate" OutputSubPath="P.O.S Informatique" />
    <VSTemplate Include="RazorComponent.vstemplate" OutputSubPath="P.O.S Informatique" />
    <VSTemplate Include="XUnitTest.vstemplate" OutputSubPath="P.O.S Informatique" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.VSSDK.BuildTools" />
  </ItemGroup>
  
  <Target Name="BeforeBuild">
    <!-- Update the version of Wizard to use -->
    <PropertyGroup>
      <_VSTemplateNamespaces>
        <Namespace Prefix="vs" Uri="http://schemas.microsoft.com/developer/vstemplate/2005" />
      </_VSTemplateNamespaces>
    </PropertyGroup>
    <XmlPoke XmlInputPath="%(VSTemplate.Identity)" Value="PosInformatique.VisualStudio.Templates, Version=$(Version), Culture=Neutral, PublicKeyToken=889b4f35d1c32a46" Query="/vs:VSTemplate/vs:WizardExtension/vs:Assembly" Namespaces="$(_VSTemplateNamespaces)" />
  </Target>
  
  <Target Name="AfterBuild">
    <!-- Restore the version of Wizard to 0.0.0.0 -->
    <PropertyGroup>
      <_VSTemplateNamespaces>
        <Namespace Prefix="vs" Uri="http://schemas.microsoft.com/developer/vstemplate/2005" />
      </_VSTemplateNamespaces>
    </PropertyGroup>
    <XmlPoke XmlInputPath="%(VSTemplate.Identity)" Value="PosInformatique.VisualStudio.Templates, Version=0.0.0.0, Culture=Neutral, PublicKeyToken=889b4f35d1c32a46" Query="/vs:VSTemplate/vs:WizardExtension/vs:Assembly" Namespaces="$(_VSTemplateNamespaces)" />
  </Target>
  
</Project>